### ISSUE TITLE
Update custom reports using the following answer templates

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#895] opened 2016-01-06 20:25 UTC
https://myapnea.org/surveys/my-sleep-apnea/baseline/report -- the "How long do you think you had sleep apnea before you were diagnosed?" portion needs to be updated to new answer template.

Check Questions:

- [x] `apnea-before-diagnosis`
- [x] `risk-symptoms`
- [x] `symptoms-before-diagnosis`
- [x] `treatment-outcomes-components`

**Comment by remomueller** [comment] 2016-04-18 21:39
Hi @mrueschman, I'll see if I can get this fixed in 10.3.0. Is it simply not pulling any values currently? Thanks

**Comment by mrueschman** [comment] 2016-04-19 11:55
It says 0%, which cannot be true.

![image](https://cloud.githubusercontent.com/assets/707167/14638170/0d1710ca-0604-11e6-9b5e-dca52b460ba7.png)

The answer options were changed for this question and I'm guessing the logic to do this proportion/percentage was not updated correctly.

**Comment by mrueschman** [comment] 2016-04-19 12:00
I'm not sure why the other questions were listed here.. there now seem to be data flowing into them, though it couldn't hurt to confirm the correct set of values are being tallied so that the reported percentages *actually* match the text on the page.

**Comment by remomueller** [comment] 2016-04-19 15:04
@mrueschman, I looked at the other questions, and they are set up correctly. The problem for "How long do you think you had sleep apnea before you were diagnosed?" was caused by the question having an archived answer template which was being used by the custom report as opposed to the new answer template. I fixed the method to only search for existing unarchived answer templates.

**Closed by remomueller** 2016-04-19 15:04 UTC
Labels: Reports, Survey
