### ISSUE TITLE
Custom report feedback on My Sleep Apnea survey is wrong

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#911] opened 2016-03-08 19:09 UTC
https://myapnea.org/surveys/my-sleep-apnea/baseline/report

![image](https://cloud.githubusercontent.com/assets/707167/13612767/42b0bf1c-e537-11e5-928d-424c782a6750.png)

This survey recently changed and it seems like the percentage for this particular question/response is wrong.

**Comment by remomueller** [comment] 2016-04-21 14:25
This is a duplicate of #895, closing.

**Comment by remomueller** [comment] 2016-04-21 16:17
Reopening, it appears the number is being calculated incorrectly

**Closed** 2016-04-21 16:27 UTC
Labels: Bug, Survey
